import { RequestTypeConfig, AcademicRequest } from '../types';

export interface AcademicDepartment {
  code: string;
  name: string;
  nameEn: string;
}

export const DEPARTMENTS: AcademicDepartment[] = [
  { code: 'GI', name: 'Génie Informatique', nameEn: 'Computer Engineering' },
  { code: 'GEII', name: 'Génie Électrique & Informatique Industrielle', nameEn: 'Electrical & Industrial Engineering' },
  { code: 'GC', name: 'Génie Civil', nameEn: 'Civil Engineering' },
  { code: 'GMP', name: 'Génie Mécanique & Productique', nameEn: 'Mechanical & Production Engineering' },
  { code: 'GIM', name: 'Génie Industriel & Maintenance', nameEn: 'Industrial & Maintenance Engineering' },
  { code: 'GEA', name: 'Gestion des Entreprises & Administrations', nameEn: 'Business & Administrative Management' },
];

export const CLASSES = [
  { id: 'DUT 1', label: 'DUT 1ère Année (DUT 1)', labelEn: 'DUT 1st Year (DUT 1)' },
  { id: 'DUT 2', label: 'DUT 2ème Année (DUT 2)', labelEn: 'DUT 2nd Year (DUT 2)' },
  { id: 'LP', label: 'Licence Professionnelle (LP)', labelEn: 'Professional Bachelor (LP)' },
];

export const REQUEST_TYPES: RequestTypeConfig[] = [
  {
    id: 'reclamation',
    code: 'REC',
    title: 'Réclamation de note (Examen / CC / TP)',
    titleEn: 'Grade Appeal (Exam / Continuous Assessment / Lab)',
    description: 'Contestation formelle d’une note affichée lors des délibérations de session normale ou de rattrapage.',
    descriptionEn: 'Formal appeal against a posted grade during regular or retake exam deliberations.',
    iconName: 'rate_review',
    badge: 'Contentieux académique',
    estimatedDelayDays: '48h à 72h',
    hasSpecificFields: true,
    requiredDocuments: [
      {
        id: 'doc_carte',
        name: 'Copie de la carte d’étudiant',
        description: 'Format PDF, JPG ou PNG valide pour l’année académique en cours (max 5 Mo).',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_releve_ou_epreuve',
        name: 'Relevé de notes concerné ou copie d’examen / émargement',
        description: 'Preuve de composition, reçu d’émargement ou capture du procès-verbal affiché.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
    ],
  },
  {
    id: 'attestation',
    code: 'ATT',
    title: 'Attestation de scolarité',
    titleEn: 'Certificate of Attendance / Enrollment',
    description: 'Document officiel certifiant votre inscription administrative et assiduité pour l’année académique en cours.',
    descriptionEn: 'Official document certifying your administrative enrollment and attendance for the current academic year.',
    iconName: 'school',
    badge: 'Acte certifié',
    estimatedDelayDays: '24h à 48h',
    requiredDocuments: [
      {
        id: 'doc_carte',
        name: 'Copie de la carte d’étudiant',
        description: 'Carte d’étudiant de l’IUT ou récépissé d’inscription en cours de validité.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_quittance',
        name: 'Quittance des droits universitaires',
        description: 'Reçu de paiement bancaire ou attestation de versement certifié par l’agence comptable.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
    ],
  },
  {
    id: 'releve',
    code: 'REL',
    title: 'Relevé de notes officiel',
    titleEn: 'Official Academic Transcript',
    description: 'Relevé de notes semestriel ou récapitulatif annuel signé par le Décanat de l’IUT de Douala.',
    descriptionEn: 'Semester or annual academic transcript officially stamped and signed by the IUT Deanery.',
    iconName: 'description',
    badge: 'Relevé officiel',
    estimatedDelayDays: '48h à 72h',
    requiredDocuments: [
      {
        id: 'doc_carte',
        name: 'Copie de la carte d’étudiant',
        description: 'Copie lisible de la carte d’étudiant ou pièce d’identité nationale.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_recu_frais',
        name: 'Quittance de paiement des frais de relevé',
        description: 'Reçu de paiement au guichet de l’agence comptable.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
    ],
  },
  {
    id: 'certificat',
    code: 'CER',
    title: 'Certificat de réussite au diplôme',
    titleEn: 'Diploma Completion Certificate',
    description: 'Attestation de réussite attestant de l’obtention définitive du DUT ou de la Licence Professionnelle.',
    descriptionEn: 'Certificate attesting successful completion and award of the DUT or Professional Bachelor degree.',
    iconName: 'workspace_premium',
    badge: 'Diplôme & Réussite',
    estimatedDelayDays: '72h ouvrées',
    requiredDocuments: [
      {
        id: 'doc_carte',
        name: 'Copie de la carte d’étudiant ou CNI',
        description: 'Pièce d’identité officielle en cours de validité.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_releve_s4',
        name: 'Relevé de fin de cycle (S4 ou S6) ou PV de délibération',
        description: 'Relevé certifiant la validation de tous les crédits académiques.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_acte_naissance',
        name: 'Copie d’acte de naissance certifiée conforme',
        description: 'Document nécessaire pour la conformité de l’état civil sur le diplôme.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
    ],
  },
  {
    id: 'changement',
    code: 'CHG',
    title: 'Changement de filière',
    titleEn: 'Department / Major Transfer Request',
    description: 'Demande de transfert académique vers un autre département au sein de l’IUT de Douala.',
    descriptionEn: 'Application for internal transfer to another academic department within IUT Douala.',
    iconName: 'alt_route',
    badge: 'Recours d’orientation',
    estimatedDelayDays: '5 à 7 jours ouvrés',
    requiredDocuments: [
      {
        id: 'doc_motivation',
        name: 'Lettre de motivation circonstanciée',
        description: 'Adressée à Monsieur le Directeur de l’IUT de Douala exposant le projet professionnel.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_carte',
        name: 'Copie de la carte d’étudiant',
        description: 'Carte d’étudiant de la filière d’origine.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
      {
        id: 'doc_notes_actuelles',
        name: 'Relevé des notes du semestre écoulé',
        description: 'Procès-verbal justifiant du niveau académique actuel.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
    ],
  },
  {
    id: 'information',
    code: 'INF',
    title: 'Demande d’informations administratives',
    titleEn: 'Administrative Inquiry & Assistance',
    description: 'Demande d’éclaircissement, régularisation d’immatriculation ou recours gracieux auprès de la Scolarité.',
    descriptionEn: 'Inquiry, matriculation verification, or general administrative petition to Academic Services.',
    iconName: 'contact_support',
    badge: 'Orientation & Support',
    estimatedDelayDays: '24h à 48h',
    requiredDocuments: [
      {
        id: 'doc_carte',
        name: 'Copie de la carte d’étudiant ou récépissé d’admission',
        description: 'Document justificatif de votre statut d’usager.',
        required: true,
        acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
        maxSizeMb: 5,
      },
    ],
  },
];

export const INITIAL_MOCK_REQUESTS: AcademicRequest[] = [
  {
    id: 'REQ-2024-0047',
    reference: 'UD/IUT/SCOL/2024/T4-088',
    createdAt: '14 Nov 2024, 09:42',
    updatedAt: '16 Nov 2024, 11:30',
    identity: {
      nom: 'EBWELE NGANDE',
      prenom: 'Patrick Hervé',
      matricule: '21G00892',
      filiere: 'Génie Informatique',
      classe: 'DUT 2',
      telephone: '+237 699 00 12 34',
      email: 'patrick.ebwele@iut-douala.cm',
    },
    requestTypeId: 'attestation',
    requestTypeTitle: 'Attestation de scolarité',
    documents: [
      {
        docConfigId: 'doc_carte',
        docName: 'Copie de la carte d’étudiant',
        fileName: 'Carte_Etudiant_2024.pdf',
        fileSize: 1258291,
        fileType: 'application/pdf',
      },
      {
        docConfigId: 'doc_quittance',
        docName: 'Quittance des droits universitaires',
        fileName: 'Quittance_Droits_2024.pdf',
        fileSize: 845200,
        fileType: 'application/pdf',
      },
    ],
    status: 'validee',
    assignedValidator: 'Dr. Samuel TITA',
    validatorTitle: 'Chef de la Division de la Scolarité & des Diplômes',
    processingTimeHours: 49,
    decisionNote: '« Votre attestation de scolarité officielle pour l’année académique 2023/2024 a été générée, codifiée et visée avec succès. Vous pouvez télécharger l’exemplaire numérique certifié ci-dessous, ou passer au Guichet 3 de la Scolarité (Campus Ndogbong) muni de votre carte d’étudiant physique pour apposition éventuelle du cachet humide original sur support papier sécurisé. »',
    decisionDate: '16/11/2024 à 11:30:19 GMT+1',
    verificationCode: 'IUT-VERIF-9821-X',
    physicalLocation: 'Campus IUT Ndogbong, Pavillon Administratif A, Rez-de-chaussée, Guichet 3',
    deliveryAvailable: true,
  },
  {
    id: 'REQ-2024-0048',
    reference: 'UD/IUT/SCOL/2024/T4-092',
    createdAt: '15 Nov 2024, 10:24',
    updatedAt: '15 Nov 2024, 14:15',
    identity: {
      nom: 'MOUKOKO',
      prenom: 'Françoise Audrey',
      matricule: '22I00412',
      filiere: 'Génie Informatique',
      classe: 'DUT 2',
      telephone: '+237 677 34 56 78',
      email: 'francoise.moukoko@iut-douala.cm',
    },
    requestTypeId: 'reclamation',
    requestTypeTitle: 'Réclamation de note (Examen / CC / TP)',
    specificDetails: {
      semester: 'Semestre 3 (S3)',
      course: 'Algorithmique & Structures de Données (UE Info 311)',
      teacher: 'Dr. Ndongo',
      currentGrade: '07/20',
      expectedGrade: '14.5/20',
      explanation: 'Monsieur le Chef de Département, ma note affichée au CC d’Algorithmique II est de 07/20 alors que le corrigé remis par le Dr. Ndongo m’attribuait 14.5/20. Ci-joint ma feuille d’évaluation paraphée.',
    },
    documents: [
      {
        docConfigId: 'doc_carte',
        docName: 'Copie de la carte d’étudiant',
        fileName: 'Carte_Etudiant_Moukoko.pdf',
        fileSize: 984000,
        fileType: 'application/pdf',
      },
      {
        docConfigId: 'doc_releve_ou_epreuve',
        docName: 'Feuille d’évaluation paraphée',
        fileName: 'Copie_CC_Algo_Paraphee.pdf',
        fileSize: 1468000,
        fileType: 'application/pdf',
      },
    ],
    status: 'en_cours',
    assignedValidator: 'Dr. Samuel TITA',
    validatorTitle: 'Chef Service Scolarité Centrale',
    processingTimeHours: 18,
    decisionNote: 'Dossier transmis au Chef de Département Informatique pour vérification matérielle du bordereau d’émargement.',
    verificationCode: 'IUT-VERIF-7721-P',
    physicalLocation: 'Campus Ndogbong, Bureau A-04 (Département Génie Informatique)',
    deliveryAvailable: false,
  },
  {
    id: 'REQ-2024-0112',
    reference: 'UD/IUT/SCOL/2024/T4-041',
    createdAt: '13 Nov 2024, 08:30',
    updatedAt: '15 Nov 2024, 10:15',
    identity: {
      nom: 'TCHINDA KAMDEM',
      prenom: 'Boris',
      matricule: '21G00415',
      filiere: 'Génie Électrique',
      classe: 'DUT 2',
      telephone: '+237 691 22 33 44',
      email: 'boris.tchinda@iut-douala.cm',
    },
    requestTypeId: 'certificat',
    requestTypeTitle: 'Certificat de réussite au diplôme',
    documents: [
      {
        docConfigId: 'doc_carte',
        docName: 'Copie de la carte d’étudiant',
        fileName: 'CNI_Tchinda.jpg',
        fileSize: 1100000,
        fileType: 'image/jpeg',
      },
      {
        docConfigId: 'doc_releve_s4',
        docName: 'Relevé de fin de cycle S4',
        fileName: 'Releve_Notes_S4_GEII.pdf',
        fileSize: 1540000,
        fileType: 'application/pdf',
      },
    ],
    status: 'validee',
    assignedValidator: 'Pr. Eboumbou',
    validatorTitle: 'Chef de Département GEII',
    processingTimeHours: 48,
    decisionNote: 'Parcours validé avec mention Assez Bien. Certificat de réussite DUT disponible au Guichet Express.',
    decisionDate: '15/11/2024 à 10:15:00 GMT+1',
    verificationCode: 'IUT-VERIF-3094-C',
    physicalLocation: 'Campus Ndogbong, Bureau A-12 (Mme Mbarga)',
    deliveryAvailable: true,
  },
  {
    id: 'REQ-2024-0050',
    reference: 'UD/IUT/SCOL/2024/T4-019',
    createdAt: '12 Nov 2024, 15:10',
    updatedAt: '13 Nov 2024, 17:00',
    identity: {
      nom: 'BELLA NGONO',
      prenom: 'Christian',
      matricule: '23M00941',
      filiere: 'Génie Mécanique',
      classe: 'DUT 1',
      telephone: '+237 655 88 99 00',
      email: 'christian.bella@iut-douala.cm',
    },
    requestTypeId: 'releve',
    requestTypeTitle: 'Relevé de notes officiel',
    documents: [
      {
        docConfigId: 'doc_carte',
        docName: 'Copie de la carte d’étudiant',
        fileName: 'Carte_Etudiant.pdf',
        fileSize: 680000,
        fileType: 'application/pdf',
      },
    ],
    status: 'refusee',
    assignedValidator: 'Dr. Samuel TITA',
    validatorTitle: 'Chef Service Scolarité Centrale',
    processingTimeHours: 26,
    decisionNote: '« Quittance de deuxième tranche des droits universitaires non retrouvée dans l’état comptable de l’Agence Comptable Centrale pour l’année 2023/2024. Veuillez soumettre une nouvelle requête en joignant le reçu bancaire original visé par la comptabilité. »',
    decisionDate: '13/11/2024 à 17:00:00 GMT+1',
    verificationCode: 'IUT-VERIF-1102-E',
    physicalLocation: 'Campus Ndogbong, Agence Comptable Centrale',
    deliveryAvailable: false,
  },
];
